PerfectCrm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from PerfectCrm import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^crm/",include("crm.urls")),
    url(r"^student/",include("student.urls")),
    url(r"^account/login/$",views.access_login,name="access_login"),
    url(r"^account/logout/$",views.access_logout,name="access_logout"),
    url(r"^king_admin/",include("king_admin.urls")),
]

crm/urls.py
from django.conf.urls import url
from crm import views
urlpatterns = [
    url(r"^$",views.index,name="sales_index"),
    # url(r"^customer/$",views.customer_list,name="customer_list"),
    url(r"^customer/(?P<nid>\d+)/enrollment",views.sale_enroll,name="sale_enroll"),
    url(r"^customer/registration/(?P<enroll_id>\d+)/(?P<random_str>\w+)/", views.stu_registration, name="stu_registration"),
    url(r"^customer/registration_back/(?P<enroll_id>\d+)/", views.stu_registration_back, name="stu_registration_back"),
    url(r"^customer/enrollment/(?P<enroll_id>\d+)/audit/", views.enroll_audit, name="enroll_audit"),
    url(r"^customer/enrollment/(?P<enroll_id>\d+)/payment/", views.enroll_payment, name="enroll_payment"),
   # url(r"^customer/enrollment/(?P<enroll_id>\d+)/reject/", views.enroll_reject, name="enroll_reject"),

]

student/urls.py
from django.conf.urls import url,include
from student import views
urlpatterns = [
    url(r"^$",views.stu_index,name="stu_index"),
    url(r"^my_class/$",views.my_class,name="my_class"),
    url(r"^my_class/study_records/(?P<enroll_id>\d+)/$",views.study_records,name="study_records"),
    url(r"^my_class/study_records/homework_detail/(?P<studyrecord_id>\d+)/$",views.homework_detail,name="homework_detail"),
    url(r"^my_class/study_records/homework_detail/(?P<studyrecord_id>\d+)/(?P<attach_id>\w+)$", views.homework_attachment_download,
        name="homework_attachment_download"),
]

crm/models.py
from django.db import models

# Create your models here.

"""
    类的创建流程:
        Customer(客户信息表)
        
"""
class Customer(models.Model):
    """
        # 客户信息表 -->特指对销售有意义的有效客户
    """
    #blank=True这个只是在django-admin中页面上限制为可以为空
    #null=True是限定数据库中可以为空
    name = models.CharField(verbose_name="客户姓名",max_length=32,blank=True,null=True)
    #因为通过qq进行的联系的客户才是有效客户
    qq = models.CharField(verbose_name="QQ",max_length=64,unique=True)
    qq_name = models.CharField(verbose_name="QQ名",max_length=64,blank=True,null=True)
    phone = models.CharField(verbose_name="联系电话",max_length=64,blank=True,null=True)
    id_num = models.CharField(verbose_name="身份证",max_length=18,blank=True,null=True)
    email = models.EmailField(verbose_name="常用邮箱",blank=True,null=True)
    source_choices = (
        (0,"转介绍"),
        (1,"QQ群"),
        (2,"官网"),
        (3,"百度推广"),
        (4,"51CTO"),
        (5,"知乎"),
        (6,"市场推广")
    )
    source = models.SmallIntegerField(verbose_name="信息来源",choices=source_choices)
    status_choices = ((0, "未报名"), (1, "已报名"))
    status = models.SmallIntegerField(verbose_name="报名状态",choices=status_choices,default=0)
    referral_from = models.CharField(verbose_name="介绍人qq",max_length=64,blank=True,null=True)
    #多对一,客户信息表中的多条记录中的咨询课程对应课程表中的一条记录
    consult_course = models.ForeignKey(to="Course",verbose_name="咨询课程")
    content = models.TextField(verbose_name="咨询详情")
    #多对多关系
    tags = models.ManyToManyField(to="Tag",blank=True,null=True)
    # 多对一,客户信息表中的多条记录中的咨询顾问对应账号表中的一条记录
    consultant = models.ForeignKey(to="UserProfile",verbose_name="咨询顾问")
    memo = models.TextField(blank=True,null=True,verbose_name="备注")
    date = models.DateTimeField(auto_now_add=True,verbose_name="咨询时间")

    def __str__(self):
        return self.qq

    class Meta:
        # verbose_name = "客户信息表"
        #如果使用verbose_name = "客户信息表"的话,那在django-admin中这个表名后面会跟上s,也就是表名的复数形式
        #如果想干掉这个s就需要使用verbose_name_plural
        verbose_name_plural = "客户信息表_Customer"

class Tag(models.Model):
    """
        标签表,与客户信息表是多对多的关系.也就是说一个客户有多个标签,一个标签可以同时作用在多个
        多个客户上
    """
    name = models.CharField(max_length=32,unique=True,verbose_name="标签名")

    class Meta:
        verbose_name_plural = "标签表_Tag"
    def __str__(self):
        return self.name

#引入django自带的认证
 # from django.contrib.auth.models import User
# class UserProfile(models.Model):
#     """
#         账号表
#     """
#     user = models.OneToOneField(User)
#     name = models.CharField(max_length=32,verbose_name="用户名")
#     #一个账号有多个角色,一个角色属于多个账号
#     roles = models.ManyToManyField(to="Role",blank=True,null=True,verbose_name="角色")
#
#     def __str__(self):
#         return "%s"%(self.user)
#
#     class Meta:
#         verbose_name_plural = "账号表_UserProfile"

#自定义用户认证
from django.contrib.auth.models import BaseUserManager,AbstractBaseUser,PermissionsMixin
#UserProfileManager还必须在UserProfile前面，UserProfile作用在于定义model对象，而UserProfileManager的作用在于
#执行创建用户或超级用户的命令 python manage.py createsuperuser中就用到下面这两个定义的类
class UserProfileManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )
        
        #设置密码，存入数据库为md5加密方式，还加了salt
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email,
            password=password,
            name=name
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

from django.utils.translation import ugettext_lazy as _

class UserProfile(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(
        verbose_name='邮箱',
        max_length=255,
        unique=True,
    )
    #重写父类的password属性，以便不修改源代码，添加一个help_text属性用于修改密码
    password = models.CharField(_('password'), max_length=128,help_text="<a href='javascript:' data-toggle='modal' data-target='#myModal'>密码修改</a>")
    name = models.CharField(verbose_name="用户名",max_length=32)
    #是否活跃，权限设置：可封禁
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    roles = models.ManyToManyField(to="Role",blank=True,verbose_name="角色")
    stu_enrollment = models.ForeignKey(to="Customer",blank=True,null=True,verbose_name="已报名的学生")
    #固定样式，只能命名为objects，将验证方法与创建user函数相关联
    objects = UserProfileManager()
    
    #指定emali作为用户名
    USERNAME_FIELD = 'email'
    #必填字段
    REQUIRED_FIELDS = ['name']

    #为认证类添加自定义的权限列表
    class Meta:
        permissions = (
                        ("crm.can_access_my_class","访问我的课程")
                       ,("crm.can_access_customer_list","访问客户库")
                       ,("crm.can_access_customer_detail","访问客户详情")
                       ,("crm.can_change_customer_detail","修改客户详情")
        )


    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    #判断权限：user是否是员工？
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Course(models.Model):
    """
        课程表
    """
    name = models.CharField(max_length=64,unique=True,verbose_name="课程名")
    #positiveIntegerField表示正数
    price = models.PositiveIntegerField(verbose_name="价格")
    period = models.PositiveIntegerField(verbose_name="周期(月)")
    outline = models.TextField(verbose_name="课程大纲")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "课程表_Course"

class Branch(models.Model):
    """
        校区
    """
    name = models.CharField(max_length=128,unique=True,verbose_name="校区名")
    addr = models.CharField(max_length=128,verbose_name="地址")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "校区表_Branch"

class ClassList(models.Model):
    """
        班级列表
    """
    branch = models.ForeignKey(to="Branch")

    course = models.ForeignKey(to="Course",verbose_name="课程")
    class_type_choices = ((0,"面授(脱产"),(1,"面授(周末)"),(2,"网络班"))
    class_type = models.SmallIntegerField(choices=class_type_choices,verbose_name="教学方式")
    #此字段在这个地方就类似于班级名称:如python全栈第2期
    semester = models.PositiveIntegerField(verbose_name="学期")
    contract = models.ForeignKey(to="Contract",verbose_name="合同",blank=True,null=True)
    teachers = models.ManyToManyField(to="UserProfile",verbose_name="老师")
    start_date = models.DateField(verbose_name="开班日期")
    end_date = models.DateField(verbose_name="结业时期",blank=True,null=True)

    class Meta:
        verbose_name_plural = "班级表_ClassList"
        #同一个校区 同一个课程 同一个学期,只能有一个班级使用,所以使用联合索引避免重复
        unique_together = ("branch","course","semester")

    def __str__(self):
        return "%s %s %s"%(self.branch,self.course,self.semester)


class CourseRecord(models.Model):
    """
        上课记录
    """
    from_class = models.ForeignKey(to="ClassList",verbose_name="班级")
    day_num = models.PositiveIntegerField(verbose_name="第几节(天)")
    teacher = models.ForeignKey(to="UserProfile",verbose_name="老师")
    has_homework = models.BooleanField(default=True,verbose_name="是否有作业")
    homework_title = models.CharField(max_length=128,blank=True,null=True)
    homework_content = models.TextField(verbose_name="作业内容",blank=True,null=True)
    outline = models.TextField(verbose_name="本节课程大纲")
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s %s"%(self.from_class,self.day_num)

    class Meta:
        verbose_name_plural = "上课记录表_CourseRecord"
        # 班级与第几天是联合唯一索引
        unique_together = ("from_class","day_num")

class StudyRecord(models.Model):
    """
        学习记录
    """
    student = models.ForeignKey(to="Enrollment",verbose_name="报名表中的学生")
    course_record = models.ForeignKey(to="CourseRecord",verbose_name="上课记录")
    attendance_choices = ((0,"已签到"),(1,"迟到"),(2,"缺勤"),(3,"早退"))
    attendance = models.SmallIntegerField(choices=attendance_choices,default=0,\
                                          verbose_name="出勤情况")

    score_choices = (
                        (100,"A+"),
                        (90,"A"),
                        (85,"B+"),
                        (80,"B"),
                        (75,"B-"),
                        (70,"C+"),
                        (60,"C"),
                        (40,"C-"),
                        #得D就要扣分了,也就是扣钱了
                        (-50,"D"),
                        #抄作业就扣100分
                        (-100,"COPY"),
                        #由于以前没有来,那以前的作业就是0分
                        (0,"N/A"),
    )
    score = models.SmallIntegerField(choices=score_choices,verbose_name="学习成绩")
    memo = models.TextField(verbose_name="批作业的备注")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s %s"%(self.student,self.course_record,self.score)

    class Meta:
        verbose_name_plural = "学习记录表_StudyRecord"
        unique_together = ("student","course_record")

class HomeworkAttachment(models.Model):

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.
from crm import models
from crm.permissions import permission


@login_required
def stu_index(request):
    return render(request,"student/stu_index.html")


# 由于使用了权限检测的装饰器，在它的里面已经对是否登录进行了判断，所以这里就需要@login_required了
@permission.check_permission
def my_class(request):
    enrollment_queryset = request.user.stu_enrollment.enrollment_set.all()
    return render(request,"student/my_class.html",{"enrollment_queryset":enrollment_queryset})

@login_required
def study_records(request,enroll_id):
    studyrecord_queryset = models.StudyRecord.objects.filter(student_id = enroll_id)
    return render(request,"student/study_records.html",{"studyrecord_queryset":studyrecord_queryset})

import os
from django.shortcuts import HttpResponse
from PerfectCrm import settings
from django.urls import reverse
@login_required
def homework_detail(request,studyrecord_id):
    studyrecord_obj = models.StudyRecord.objects.get(id=studyrecord_id)
    homework_attach_objs = models.HomeworkAttachment.objects.filter(study_record=studyrecord_obj).all()

    if request.method == "POST":
        # 判断是否是ajax发送过来的数据，这里用来判断是否是上传图片
        if request.is_ajax():
            if request.POST.get("type") == "delete":
                file_name = request.POST.get("file_name")
                file_path = os.path.join(settings.STUDYRECORD_DATA, studyrecord_id, file_name)
                if os.path.isfile(file_path):
                    os.remove(file_path)
                    models.HomeworkAttachment.objects.filter(attachment_url=file_path).delete()
                    return HttpResponse("文件%s删除成功" % file_name);
                else:
                    return HttpResponse(file_name + "不存在")

            file_obj = request.FILES.get("file")
            if not os.path.exists(settings.STUDYRECORD_DATA):
                os.mkdir(settings.STUDYRECORD_DATA)
            # 相当于mkdir -P
            os.makedirs(os.path.join(settings.STUDYRECORD_DATA, studyrecord_id), exist_ok=True)
            file_path = os.path.join(settings.STUDYRECORD_DATA, studyrecord_id, file_obj.name)
            with open(file_path, "wb") as f:
                for chunk in file_obj.chunks():
                    f.write(chunk)

            if(models.HomeworkAttachment.objects.filter(study_record=studyrecord_obj,attachment_url=file_path)).all():
                attach_obj = models.HomeworkAttachment.objects.get(study_record=studyrecord_obj,attachment_url=file_path)
            else:
                attach_obj = models.HomeworkAttachment.objects.create(study_record=studyrecord_obj,
                                                                             attachment_url=file_path)
            attach_url = reverse("homework_attachment_download",
                                 kwargs={"studyrecord_id": studyrecord_obj.id, "attach_id": attach_obj.id})
            print("-------------",attach_url)
            return HttpResponse(attach_url)

    return render(request,"student/homework_detail.html",{"studyrecord_obj":studyrecord_obj,"homework_attach_objs":homework_attach_objs})

from django.http import StreamingHttpResponse
@login_required
def homework_attachment_download(request,studyrecord_id,attach_id):
    '''
        文件下载
    '''

    def file_iterator(file_path, chunk_size=512):
        with open(file_path,"rb") as f:
            while True:
                c = f.read(chunk_size)
                if c:
                    yield c
                else:
                    break

    homework_attachment_obj = models.HomeworkAttachment.objects.get(id=attach_id)
    file_path = homework_attachment_obj.attachment_url
    file_name = os.path.basename(file_path)
    response = StreamingHttpResponse(file_iterator(file_path))

    response['Content-Type'] = 'application/octet-stream'
    disposition = 'attachment;filename="%s"' % file_name
    response['Content-Disposition'] = disposition.encode(encoding="utf-8")
    return response

templates/student/homework_detail.html
{% extends "student/stu_index.html" %}
{% load stu_tags %}
{% block page-content %}

    <div class="panel panel-default">

  <!-- Default panel contents -->
  <div class="panel-heading">我的课程</div>

    <div class="panel-body">
        <h4>作业标题:{{ studyrecord_obj.course_record.homework_title }}</h4>
        <h4>作业详情：</h4><pre style="min-height: 400px;">{{ studyrecord_obj.course_record.homework_content }}</pre>
        <h4>老师评语：{{ studyrecord_obj.memo }}</h4>
        <h4>本节成绩：{{ studyrecord_obj.score }}</h4>
        <hr>
        <div id="alert_area">
        <!--已上传附件区-->
            {% for attach_obj in homework_attach_objs %}
                {% render_attach attach_obj forloop.counter0 %}
            {% endfor %}
        </div>
        <p>
                <form action="./" class="dropzone" id="myAwesomeDropzone" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="page" value="2">
{#                    <div class="fallback">#}
{#                        <input name="file" type="file" multiple/>#}
{#                    </div>#}
                    <div class="dz-default dz-message needsclick">
                        <div class="dz-icon icon-wrap icon-circle icon-wrap-md">
                            <i class="fa fa-cloud-upload fa-3x"></i>
                        </div>
                    <div>
                        <p class="dz-text">请上传课程作业</p>
                        <p class="text-muted">仅支持tar包文件</p>
                    </div>
        </div>
                </form>
                <form id="form_2" action="/account/login/" method="get" onsubmit="return PreSubmit_1();"></form>
                </p>
    </div>
</div>
{% endblock %}
{% block css %}
    <link href="/static/css/dropzone.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
{% endblock %}
{% block js %}
    <script src="/static/js/dropzone.js"></script>
    <script src="/static/js/fastclick.js"></script>
    <script src="/static/js/jquery.cookie.js"></script>
     <script>
       FastClick.attach(document.body);
        file_count = 0;
        alert_list = ["alert-info","alert-success","alert-danger"];

        Dropzone.options.myAwesomeDropzone = {
            paramName: "file", // The name that will be used to transfer the file
            maxFilesize: 50, // MB
            maxFiles: 10,
{#            dictDefaultMessage: "请上传课程作业",#}
            dictFileTooBig: "文件大小不能超过50M",
{#            addRemoveLinks: true,#}
            addRemoveLinks:false,
            dictRemoveLinks: "x",
            dictCancelUpload: "x",
            accept: function (file, done) {
                if (file.name == "justinbieber.jpg") {
                    done("Naha, you don't.");
                }
                else {
                    done();
                }
            },
            init: function () {
                //上传文件是判断文件的个是是否大于1
                this.on("addedfile", function (file) {
                    console.log("----------",this.files);
                    //上传文件时触发的事件
                    file_count = this.files.length;
{#                    if(file_count>1){#}
{#                        alert("文件数量不能超过1个");#}
{#                        this.removeFile(file);#}
{#                    }#}
                    if(!this.files[0].name.match("tar")){
                        alert("仅支持tar文件包相关格式");
                        console.log("sadfffffff",file);
                        this.removeFile(file);
                    }
                });
                this.on("queuecomplete", function (file) {
                    //上传完成后触发的方法

                });
                this.on("success", function (file,result) {
                    var alert_color = alert_list[file_count%3];
                    console.log(alert_color);
                    $("#alert_area").append('<div class="alert '+alert_color+' alert-dismissable" style="display: inline-block;margin-left:5px;">\n' +
                        '                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">\n' +
                        '                                &times;\n' +
                        '                            </button> <a href='+result+' >'+file.name+'</a>\n' +
                        '                        </div>');


                });

                this.on("removedfile", function (file) {
                    console.log("File " + file.name + "removed");
                });
            }
        };

        //已上传文件的删除操作
        $("#alert_area").delegate(".alert","close.bs.alert", function () {
            file_name = $(this).children().eq(1).text();
            for(var i =0;i<$("[data-dz-name]").length;i++){
                var tag = $("[data-dz-name]").eq(i);
                if(tag.text() == file_name){
                  tag.parent().parent().parent().remove();
                }
            }
            $.ajax({
                        type: 'post',
                        url: "./",
                        data:{"type":"delete","file_name":file_name},
                        headers:{"X-CSRFtoken":$.cookie("csrftoken")},
                        success: function (result) {
                            alert(result);

                        }
                    });
	    });


    </script>
{% endblock %}

templates/student/my_class.html
{% extends "student/stu_index.html" %}
{% load stu_tags %}
{% block page-content %}

    <div class="panel panel-default">

  <!-- Default panel contents -->
  <div class="panel-heading">我的课程</div>

  <!-- Table -->
  <table class="table table-hover table-responsive">
    <thead>
        <tr>
            <td>课程名称</td>
            <td>班级</td>
            <td>开课日期</td>
            <td>结业日期</td>
            <td>课程进度</td>
            <td>我的成绩</td>
            <td>作业管理</td>
        </tr>
    </thead>
      <tbody>
      {% for enroll_obj in enrollment_queryset %}
          <tr>
            <td>{{ enroll_obj.enrolled_class.course.name }}</td>
          <td>{{ enroll_obj.enrolled_class.semester }}</td>
          <td>{{ enroll_obj.enrolled_class.start_date }}</td>
          <td>{{ enroll_obj.enrolled_class.end_date }}</td>
          <td>{{ enroll_obj.studyrecord_set.count }}</td>
          <td>{% score_total enroll_obj %}</td>
              <!--通过报名的id来获取学习记录-->
          <td><a href='{% url "study_records" enroll_obj.id %}'>作业管理</a></td>
          </tr>
      {% endfor %}


      </tbody>

  </table>
</div>
{% endblock %}

templates/student/stu_index.html
{% extends "base.html" %}
{% block content %}
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://v3.bootcss.com/examples/dashboard/#">PerfectCRM</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              <!--在完成自定义认证后，UserProfile表就成为了认证表，而在request中它对应的就是user-->
{#            <li><a href="http://v3.bootcss.com/examples/dashboard/#">{{ request.user.userprofile.name }}</a></li>#}
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    {{ request.user.name }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">编辑</a></li>
                        <li><a href="{% url "access_logout" %}">注销</a></li>
                    </ul>
                </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
              {% for role in request.user.roles.all %}
                  {% for menu in role.menus.all %}
                      <li><a href="{% if menu.url_type == 0 %}{% url menu.url_name %}{% else %}{{ menu.url_name }}{% endif %}">{{ menu.name }}</a></li>
                  {% endfor %}
              {% endfor %}
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          {% block page-content %}
          {% endblock %}
        </div>

      </div>
    </div>
{% endblock %}

templates/student/study_records.html
{% extends "student/stu_index.html" %}
{% load stu_tags %}
{% block page-content %}

    <div class="panel panel-default">

  <!-- Default panel contents -->
  <div class="panel-heading">我的课程</div>

  <!-- Table -->
  <table class="table table-hover table-responsive">
    <thead>
        <tr>
            <td>课程节次</td>
            <td>上课日期</td>
            <td>是否有作业</td>
            <td>作业标题</td>
            <td>签到状态</td>
            <td>成绩</td>
            <td>作业管理</td>
        </tr>
    </thead>
      <tbody>
      {% for studyrecord in studyrecord_queryset %}
          <tr>
            <td>{{ studyrecord.course_record.day_num }}</td>
          <td>{{ studyrecord.course_record.date }}</td>
          <td>{{ studyrecord.course_record.has_homework }}</td>
          <td>{{ studyrecord.course_record.homework_title }}</td>
              <!--通过get_字段_display的这种方式获取到choice字段对应的中文值-->
          <td>{{ studyrecord.get_attendance_display }}</td>
          <td>{{ studyrecord.get_score_display }}</td>
          <td><a href='{% url "homework_detail" studyrecord.id %}'>作业管理</a></td>
          </tr>
      {% endfor %}


      </tbody>

  </table>
</div>
{% endblock %}